root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = ["/mock-servers/data/"]
  bin = "mock-servers"
  full_bin = "/usr/local/bin/mock-servers"
  cmd = "echo 'built succesfully'"
  delay = 5000
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = false
  include_dir = ["data"]
  include_ext = ["yaml", "json", "xml", "png", "jpg", "jpeg", "pdf"]
  include_file = []
  kill_delay = "1s"
  log = "build-errors.log"
  poll = false
  poll_interval = 500
  post_cmd = []
  pre_cmd = []
  rerun = true
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
